import { chromium } from 'playwright'
const URL = 'http://localhost:5173/'
const b = await chromium.launch({ headless: true, proxy: { server: 'http://127.0.0.1:7890', bypass: 'localhost,127.0.0.1,::1,[::1]' } })
const ctx = await b.newContext({ viewport: { width: 1280, height: 950 }, locale: 'zh-CN' })
const p = await ctx.newPage()
await p.goto(URL, { waitUntil: 'domcontentloaded' })
await p.evaluate(async () => { try { localStorage.clear() } catch {}; const ds = (await indexedDB.databases?.()) || [{ name: 'fantasy-traveler' }]; await Promise.all(ds.map((d) => new Promise((r) => { const q = indexedDB.deleteDatabase(d.name); q.onsuccess = q.onerror = q.onblocked = () => r() }))) })
await p.reload({ waitUntil: 'networkidle' })
await p.evaluate(() => document.fonts.ready).catch(() => {})
await p.waitForSelector('.modal')
await p.fill('input[placeholder="旅人"]', '阿旅')
await p.locator('.modal-actions button', { hasText: '开始冒险' }).click()
await p.waitForSelector('.todo-add')
await p.locator('.tabbar button', { hasText: '副本' }).click()
await p.locator('button', { hasText: '开始副本' }).click()
await p.waitForSelector('.quest-card', { timeout: 15000 })
await p.evaluate(() => window.scrollTo(0, 0))
await p.waitForTimeout(400)
await p.locator('.battle-stage').screenshot({ path: '/tmp/ftqa_phaseCD/queststage-closeup.png' })
console.log('done')
await b.close()
